# -*- coding: utf-8 -*-
"""factorial.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13juPGIf7QJ4WwC1cgSigdk5iOf92n2ru
"""

n=5
fact=1
for i in range(1,n+1):
  fact = fact*i
  print(fact)